version: "3.9"

services:

  driller-worker:
    image: ghcr.io/andrewrutherfoord/neorepro-msr-tool/driller:latest
    restart: unless-stopped
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_BROKER_DB: ${REDIS_BROKER_DB:-1}
      NEO4J_HOST: ${NEO4J_HOST:-neo4j}
      NEO4J_PORT: ${NEO4J_PORT:-7687}
      BACKEND_URL: ${BACKEND_URL}
      TASK_SOFT_TIME_LIMIT: ${TASK_SOFT_TIME_LIMIT}
      TASK_TIME_LIMIT: ${TASK_TIME_LIMIT}
      CELERY_VISIBILITY_TIMEOUT: ${CELERY_VISIBILITY_TIMEOUT:-}
    volumes:
      - ./volumes/repos:/app/repositories
    command: >
      celery -A src.celery_app worker
      --loglevel=info
      --concurrency=1
      -Q driller_queue